# Generated by Django 2.2.7 on 2019-11-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0003_auto_20191107_0839'),
        ('agent', '0002_auto_20191107_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data e fillimit')),
                ('end_date', models.DateField(verbose_name='Data e mbarimit')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='agent.Customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='service.Service')),
            ],
            options={
                'verbose_name': 'abonimi',
                'verbose_name_plural': 'abonimet',
                'db_table': 'Subscription',
            },
        ),
    ]
