# Generated by Django 2.2.7 on 2019-11-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191104_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servis', 'verbose_name_plural': 'Servise'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Tip Servisi', 'verbose_name_plural': 'Tipe Servisesh'},
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
        migrations.AlterModelTable(
            name='servicetype',
            table='service_type',
        ),
    ]
