# Generated by Django 4.2.5 on 2023-10-03 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20191107_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Service Type', 'verbose_name_plural': 'Service Types'},
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='service.servicetype'),
        ),
    ]
