# Generated by Django 2.2.7 on 2019-11-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klientët'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
